name: testing

on:
  pull_request:
  push:
    branches:
      - 'forgejo*'
      - 'v*/forgejo*'

jobs:
  test-unit:
    if: ${{ !startsWith(vars.ROLE, 'forgejo-') }}
    runs-on: docker
    container:
      image: 'docker.io/node:20-bookworm'
    services:
      jaeger:
        image: docker.io/jaegertracing/all-in-one:1.58
        env:
          COLLECTOR_OTLP_ENABLED: true
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v3
      - uses: https://code.forgejo.org/actions/setup-go@v4
        with:
          go-version: "1.22"
      - run: |
          git config --add safe.directory '*'
          adduser --quiet --comment forgejo --disabled-password forgejo
          chown -R forgejo:forgejo .
      - name: install git >= 2.42
        run: |
          export DEBIAN_FRONTEND=noninteractive
          echo deb http://deb.debian.org/debian/ testing  main > /etc/apt/sources.list.d/testing.list
          apt-get update -qq
          apt-get -q install -qq -y git
          rm /etc/apt/sources.list.d/testing.list
          apt-get update -qq
      - run: |
          su forgejo -c 'make deps-backend'
      - run: |
          su forgejo -c 'make backend'
        env:
          TAGS: bindata
      - run: |
          su forgejo -c "make GO_TEST_PACKAGES='code.gitea.io/gitea/routers/install/...' GOTESTFLAGS='-test.v -test.run=TestOtelChi' unit-test-coverage"
        timeout-minutes: 50
        env:
          RACE_ENABLED: 'true'
          TAGS: bindata
          TEST_ELASTICSEARCH_URL: http://elasticsearch:9200
          TEST_OTEL_URL: http://jaeger:4317
