platform: linux/amd64

depends_on:
- testing-amd64

pipeline:
  fetch-tags:
    image: docker:git
    pull: true
    commands:
     - git config --add safe.directory '*'
     - git fetch --tags --force

  publish:
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      platforms: linux/amd64
      registry:
        from_secret: domain
      tag: ${CI_COMMIT_TAG##v}
      repo: ${CI_REPO_LINK##https://}
      password:
        from_secret: releaseteamtoken
      username:
        from_secret: releaseteamuser
    when:
      event: tag
