platform: linux/amd64

branches:
  exclude: [ main, release/*, soft-fork/*/*, soft-fork/*/*/*, doc-* ]

depends_on:
- testing-amd64

variables:
 - &git_image 'docker:git'
 - &dind_image 'docker:20.10-dind'
 - &buildx_image 'woodpeckerci/plugin-docker-buildx'
 - &integration_image 'codeberg.org/forgejo-integration/forgejo'

pipeline:
  fetch-tags:
    image: *git_image
    pull: true
    commands:
     - git config --add safe.directory '*'
     - git fetch --tags --force

  publish-integration:
    image: *buildx_image
    pull: true
    settings:
      platforms: linux/amd64
      registry:
        from_secret: domain
      tag: ${CI_COMMIT_TAG##v}
      repo: *integration_image
      password:
        from_secret: releaseteamtoken
      username:
        from_secret: releaseteamuser
    when:
      event: tag

  publish:
    image: *dind_image
    environment:
      INTEGRATION_IMAGE: *integration_image
    commands:
      - apk --update --no-cache add coredns
      - ( echo ".:53 {" ; echo "  forward . /etc/resolv.conf"; echo "}" ) > /etc/coredns/Corefile
      - coredns -conf /etc/coredns/Corefile &
      - /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock --dns 172.17.0.3 &
      - for i in $$(seq 60) ; do DOCKER_HOST=unix:///var/run/docker.sock docker version && break ; sleep 1 ; done
      - tag=${CI_COMMIT_TAG##v}
      - short_tag=$${tag%.*-*}
      - docker pull $${INTEGRATION_IMAGE}':'$$tag
      - docker login -p "$RELEASETEAMTOKEN" -u "$RELEASETEAMUSER" $DOMAIN
      - docker tag $${INTEGRATION_IMAGE}':'${CI_COMMIT_TAG##v} ${CI_REPO_LINK##https://}':'$$tag
      - docker push ${CI_REPO_LINK##https://}':'$$tag
      - docker tag $${INTEGRATION_IMAGE}':'${CI_COMMIT_TAG##v} ${CI_REPO_LINK##https://}':'$$short_tag
      - docker push ${CI_REPO_LINK##https://}':'$$short_tag
    secrets:
      - releaseteamtoken
      - releaseteamuser
      - domain
    when:
      event: tag
