platform: linux/amd64

branches:
  exclude: [ main, release/*, soft-fork/*/*, soft-fork/*/*/*, doc-* ]

depends_on:
- testing-amd64

pipeline:
  fetch-tags:
    image: docker:git
    pull: true
    commands:
     - git config --add safe.directory '*'
     - git fetch --tags --force

  publish-integration:
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      platforms: linux/amd64
      registry:
        from_secret: domain
      tags: ${CI_COMMIT_TAG##v}
      repo: codeberg.org/forgejo-integration/forgejo
      password:
        from_secret: releaseteamtoken
      username:
        from_secret: releaseteamuser
    when:
      event: tag

  publish:
    image: woodpeckerci/plugin-docker-buildx
    commands:
      - apk --update --no-cache add coredns
      - ( echo ".:53 {" ; echo "  forward . /etc/resolv.conf"; echo "}" ) > /etc/coredns/Corefile
      - coredns -conf /etc/coredns/Corefile &
      - /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock --dns 172.17.0.3 &
      - for i in $$(seq 60) ; do DOCKER_HOST=unix:///var/run/docker.sock docker version && break ; sleep 1 ; done
      - docker pull codeberg.org/forgejo-integration/forgejo':'${CI_COMMIT_TAG##v}
      - docker login -p "$RELEASETEAMTOKEN" -u "$RELEASETEAMUSER" $DOMAIN
      - docker tag codeberg.org/forgejo-integration/forgejo':'${CI_COMMIT_TAG##v} ${CI_REPO_LINK##https://}':'${CI_COMMIT_TAG##v}
      - docker push ${CI_REPO_LINK##https://}':'${CI_COMMIT_TAG##v}
#    environment:
#      - PLUGIN_DRY_RUN=true
#      - PLUGIN_TAG=sometag
#      - PLUGIN_DOCKERFILE=Dockerfile.noop
    secrets:
      - releaseteamtoken
      - releaseteamuser
      - domain
    when:
      event: tag
