platform: linux/amd64

branches:
  includes: [ wip-ci-* ]

when:
  event: push

variables:
 - &dind_image 'docker:20.10-dind'

pipeline:
  container-images-pull-verify-push:
    image: *dind_image
    commands:
# arm64 would require qemu-user-static which is not available on alpline
# the test coverage does not change much and running the tests test locally
# is possible if there is a doubt
      - ARCHS=amd64 ./releases/container-images-pull-verify-push.sh test
      - ./releases/container-images-pull-verify-push.sh test_teardown
    secrets:
      - releaseteamuser
      - releaseteamtoken
      - domain
