platform: linux/amd64

branches:
  exclude: [ main, release/*, soft-fork/*/*, soft-fork/*/*/*, doc-* ]

depends_on:
- compliance

variables:
 - &git_image 'docker:git'
 - &golang_image 'golang:1.19'
 - &gitea_test_image 'gitea/test_env:linux-amd64'
 - &mysql_image 'mysql:8'
 - &pgsql_image 'postgres:10'

services:
  mysql8:
    image: *mysql_image
    pull: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: testgitea

  pgsql:
    image: *pgsql_image
    pull: true
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres

workspace:
  base: /go
  path: src/codeberg/gitea

pipeline:
  fetch-tags:
    image: *git_image
    pull: true
    commands:
    - git config --add safe.directory '*'
    - git fetch --tags --force

  deps-backend:
    image: *golang_image
    pull: true
    commands:
    - make deps-backend

  tag-pre-condition:
    image: *git_image
    pull: true
    commands:
    - git update-ref refs/heads/tag_test ${CI_COMMIT_SHA}

  prepare-test-env:
    image: *gitea_test_image
    pull: true
    commands:
    - ./build/test-env-prepare.sh

  build:
    image: *gitea_test_image
    environment:
    - GOSUMDB=sum.golang.org
    - TAGS=bindata sqlite sqlite_unlock_notify
    commands:
    - su gitea -c './build/test-env-check.sh'
    - su gitea -c 'make backend'

  unit-test:
    image: *gitea_test_image
    environment:
    - TAGS=bindata sqlite sqlite_unlock_notify
    - RACE_ENABLED=true
    secrets:
    - github_read_token
    commands:
    - su gitea -c 'make unit-test-coverage test-check'

  test-mysql8:
    group: integration
    image: *gitea_test_image
    commands:
      - su gitea -c 'timeout -s ABRT 50m make test-mysql8-migration test-mysql8'
    environment:
      - TAGS=bindata
      - RACE_ENABLED=true
      - USE_REPO_TEST_DIR=1

  test-pgsql:
    group: integration
    image: *gitea_test_image
    commands:
      - su gitea -c 'timeout -s ABRT 50m make test-pgsql-migration test-pgsql'
    environment:
      - TAGS=bindata
      - RACE_ENABLED=true
      - USE_REPO_TEST_DIR=1

  test-sqlite:
    group: integration
    image: *gitea_test_image
    environment:
    - USE_REPO_TEST_DIR=1
    - GOPROXY=off
    - TAGS=bindata gogit sqlite sqlite_unlock_notify
    - TEST_TAGS=bindata gogit sqlite sqlite_unlock_notify
    commands:
    - su gitea -c 'timeout -s ABRT 120m make test-sqlite-migration test-sqlite'
