platform: linux/amd64

branches:
  exclude: [ main, release/*, soft-fork/*/*, soft-fork/*/*/*, doc-* ]

depends_on:
- compliance

workspace:
  base: /go
  path: src/codeberg/gitea

pipeline:
  fetch-tags:
    image: docker:git
    pull: true
    commands:
    - git config --add safe.directory '*'
    - git fetch --tags --force

  deps-backend:
    image: golang:1.19
    pull: true
    commands:
    - make deps-backend

  tag-pre-condition:
    image: drone/git
    pull: true
    commands:
    - git update-ref refs/heads/tag_test ${CI_COMMIT_SHA}

  prepare-test-env:
    image: gitea/test_env:linux-amd64
    pull: true
    commands:
    - ./build/test-env-prepare.sh

  build:
    image: gitea/test_env:linux-amd64
    environment:
    - GOSUMDB=sum.golang.org
    - TAGS=bindata sqlite sqlite_unlock_notify
    commands:
    - su gitea -c './build/test-env-check.sh'
    - su gitea -c 'make backend'

  unit-test:
    image: gitea/test_env:linux-amd64
    environment:
    - TAGS=bindata sqlite sqlite_unlock_notify
    - RACE_ENABLED=true
    secrets:
    - github_read_token
    commands:
    - su gitea -c 'make unit-test-coverage test-check'

  test-sqlite:
    image: gitea/test_env:linux-amd64
    environment:
    - USE_REPO_TEST_DIR=1
    - GOPROXY=off
    - TAGS=bindata gogit sqlite sqlite_unlock_notify
    - TEST_TAGS=bindata gogit sqlite sqlite_unlock_notify
    commands:
    - su gitea -c 'timeout -s ABRT 120m make test-sqlite-migration test-sqlite'
